package com.dataespresso.squarechess

import android.content.Intent
import android.net.Uri
import androidx.activity.compose.BackHandler
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.platform.LocalSoftwareKeyboardController
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Composable fun HelpAboutScreen(gameMode: String?, onExit: ()->Unit, emailHandoff: FeedbackEmailHandoff? = null) {
    val context=LocalContext.current
    val focus=LocalFocusManager.current
    val keyboard=LocalSoftwareKeyboardController.current
    var page by rememberSaveable { mutableStateOf("home") }
    var form by rememberSaveable { mutableStateOf("bug") }
    var what by rememberSaveable { mutableStateOf("") }
    var steps by rememberSaveable { mutableStateOf("") }
    var expected by rememberSaveable { mutableStateOf("") }
    var suggestion by rememberSaveable { mutableStateOf("") }
    var why by rememberSaveable { mutableStateOf("") }
    var diagnostics by rememberSaveable { mutableStateOf(true) }
    var previewSubject by rememberSaveable { mutableStateOf("") }
    var previewBody by rememberSaveable { mutableStateOf("") }
    var generated by rememberSaveable { mutableStateOf("") }
    var notice by rememberSaveable { mutableStateOf("") }
    var launching by remember { mutableStateOf(false) }
    val handoff=remember(emailHandoff,context) { emailHandoff ?: FeedbackEmailHandoff { context.startActivity(it) } }
    val lifecycle=LocalLifecycleOwner.current.lifecycle
    DisposableEffect(lifecycle,handoff) {
        val observer=LifecycleEventObserver { _, event ->
            if(event==Lifecycle.Event.ON_RESUME) { handoff.returned(); launching=false }
        }
        lifecycle.addObserver(observer)
        onDispose { lifecycle.removeObserver(observer) }
    }
    fun back() {
        focus.clearFocus(); keyboard?.hide(); notice=""
        page=when(page) {
            "home" -> { onExit(); "home" }
            "preview" -> form
            "notices","gpl","chesslib","art" -> "licences"
            else -> "home"
        }
    }
    BackHandler { back() }
    val title=when(page) {
        "bug"->R.string.report_bug; "feature"->R.string.suggest_feature; "preview"->R.string.review_message
        "about"->R.string.about_title; "privacy"->R.string.privacy_title; "info"->R.string.app_information
        "licences"->R.string.licences_title; "notices"->R.string.licence_notices
        "gpl"->R.string.licence_gpl; "chesslib"->R.string.licence_chesslib; "art"->R.string.licence_art
        else->R.string.help_title
    }
    Column(Modifier.fillMaxSize().padding(horizontal=16.dp)) {
        Row(Modifier.fillMaxWidth().padding(vertical=4.dp),verticalAlignment=Alignment.CenterVertically) {
            TextButton(onClick={back()},modifier=Modifier.heightIn(min=48.dp)) { Text(stringResource(R.string.help_back)) }
            Text(stringResource(title),fontSize=20.sp,fontWeight=FontWeight.Medium,
                modifier=Modifier.weight(1f).semantics { heading() })
        }
        key(page) {
            Column(Modifier.weight(1f).fillMaxWidth().verticalScroll(rememberScrollState()).padding(bottom=20.dp),
                verticalArrangement=Arrangement.spacedBy(12.dp)) {
                when(page) {
                    "home" -> {
                        Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)) {
                            Image(painterResource(R.drawable.ic_square_chess),null,Modifier.size(40.dp))
                            Column { Text("Square Chess",fontSize=20.sp); Text(stringResource(R.string.help_tagline),fontSize=14.sp) }
                        }
                        HelpAction(R.string.report_bug) { page="bug" }
                        HelpAction(R.string.suggest_feature) { page="feature" }
                        HorizontalDivider()
                        HelpAction(R.string.about_title) { page="about" }
                        HelpAction(R.string.privacy_title) { page="privacy" }
                        HelpAction(R.string.licences_title) { page="licences" }
                        HelpAction(R.string.app_information) { page="info" }
                        Text(stringResource(R.string.made_by),fontSize=13.sp)
                    }
                    "about" -> {
                        Text(stringResource(R.string.about_story))
                        Text(stringResource(R.string.how_to_play),fontWeight=FontWeight.Bold,modifier=Modifier.semantics { heading() })
                        Text(stringResource(R.string.play_instructions))
                    }
                    "info" -> {
                        val info=remember { appInformation(context) }
                        SelectionContainer { Text(stringResource(R.string.app_info_details,info.name,info.version,SupportConfig.email)) }
                        HelpAction(R.string.copy_support) { copyFeedback(context,"Support",SupportConfig.email);notice=context.getString(R.string.address_copied) }
                    }
                    "privacy" -> {
                        Text(stringResource(R.string.privacy_details))
                        val url=SupportConfig.privacyPolicyUrl
                        if(url==null) Text(stringResource(R.string.privacy_not_published))
                        else HelpAction(R.string.open_privacy) {
                            runCatching { context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(url))) }
                                .onFailure { notice=context.getString(R.string.privacy_open_failed) }
                        }
                    }
                    "licences" -> {
                        Text(stringResource(R.string.licences_intro))
                        HelpAction(R.string.licence_notices) {page="notices"}
                        HelpAction(R.string.licence_gpl) {page="gpl"}
                        HelpAction(R.string.licence_chesslib) {page="chesslib"}
                        HelpAction(R.string.licence_art) {page="art"}
                    }
                    "notices","gpl","chesslib","art" -> {
                        val path=when(page) { "gpl"->"licences/Stockfish-GPLv3.txt"; "chesslib"->"licences/Chesslib-Apache-2.0.txt"; "art"->"pieces/LICENSE.txt"; else->"licences/NOTICES.txt" }
                        val contents by produceState("",path) {
                            value=withContext(Dispatchers.IO) { context.assets.open(path).bufferedReader().use { it.readText() } }
                        }
                        SelectionContainer { Text(contents,fontSize=14.sp) }
                    }
                    "bug","feature" -> {
                        val bug=page=="bug"
                        if(bug) {
                            FeedbackField(R.string.bug_what,what,{what=it})
                            FeedbackField(R.string.bug_steps,steps,{steps=it})
                            FeedbackField(R.string.bug_expected,expected,{expected=it})
                            Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically) {
                                Text(stringResource(R.string.include_diagnostics),Modifier.weight(1f))
                                Switch(diagnostics,{diagnostics=it},Modifier.semantics { contentDescription=context.getString(R.string.include_diagnostics) })
                            }
                            Text(stringResource(R.string.diagnostics_explanation),fontSize=14.sp)
                        } else {
                            FeedbackField(R.string.feature_what,suggestion,{suggestion=it})
                            FeedbackField(R.string.feature_why,why,{why=it})
                        }
                        Button(enabled=if(bug) what.isNotBlank() else suggestion.isNotBlank(),
                            modifier=Modifier.fillMaxWidth().heightIn(min=48.dp),onClick={
                                val report=if(bug) FeedbackReportBuilder.bug(what,steps,expected,
                                    if(diagnostics) feedbackDiagnostics(context,gameMode) else null)
                                else FeedbackReportBuilder.feature(suggestion,why)
                                val fingerprint=report.copyText()
                                if(generated!=fingerprint) { previewSubject=report.subject;previewBody=report.body;generated=fingerprint }
                                form=page;page="preview";notice="";focus.clearFocus();keyboard?.hide()
                            }) {Text(stringResource(R.string.review_message))}
                    }
                    "preview" -> {
                        Text(stringResource(R.string.email_recipient,SupportConfig.email))
                        Text(stringResource(R.string.email_explanation),fontSize=14.sp)
                        OutlinedTextField(previewSubject,{previewSubject=FeedbackReportBuilder.subject(it)},singleLine=true,
                            label={Text(stringResource(R.string.email_subject))},modifier=Modifier.fillMaxWidth())
                        FeedbackField(R.string.email_body,previewBody,{previewBody=it},minLines=6,maxLength=30_000)
                        Button(enabled=!launching && previewSubject.isNotBlank() && previewBody.isNotBlank(),
                            modifier=Modifier.fillMaxWidth().heightIn(min=48.dp),onClick={
                                if(!launching) {
                                    focus.clearFocus();keyboard?.hide();launching=true
                                    val opened=handoff.open(FeedbackReport(previewSubject,previewBody))
                                    notice=context.getString(if(opened) R.string.email_opened else R.string.email_unavailable)
                                    if(!opened) launching=false
                                }
                            }) { Text(stringResource(R.string.send_email_app)) }
                        HelpAction(R.string.copy_report) {
                            copyFeedback(context,"Square Chess feedback",FeedbackReport(previewSubject,previewBody).copyText())
                            notice=context.getString(R.string.report_copied)
                        }
                        HelpAction(R.string.copy_support) { copyFeedback(context,"Support",SupportConfig.email);notice=context.getString(R.string.address_copied) }
                    }
                }
                if(notice.isNotBlank()) Text(notice,modifier=Modifier.semantics { liveRegion=LiveRegionMode.Polite })
            }
        }
    }
}

@Composable private fun HelpAction(label: Int,onClick: ()->Unit) {
    OutlinedButton(onClick=onClick,modifier=Modifier.fillMaxWidth().heightIn(min=52.dp),
        contentPadding=PaddingValues(horizontal=16.dp,vertical=12.dp)) {
        Text(stringResource(label),Modifier.fillMaxWidth())
    }
}
@Composable private fun FeedbackField(label: Int,value: String,onChange: (String)->Unit,minLines: Int=2,maxLength: Int=8_000) {
    val text=stringResource(label)
    OutlinedTextField(value,{onChange(it.take(maxLength))},label={Text(text)},minLines=minLines,maxLines=maxOf(6,minLines+2),
        modifier=Modifier.fillMaxWidth().semantics { contentDescription=text })
}
